### PR TITLE
Adds homepage UI elements with static data

### PR DESCRIPTION
**Pull request by horatiubota**
Adds homepage UI elements, as discussed in https://github.com/code4romania/seismic-risc-client/issues/8. Uses static data and a basic Here Maps component.

Also updates favicons using logo graphics (see [design spec](https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1)).

screenshot

### CODE REVIEW

**Review by iuliux — COMMENTED** [review]
LGTM

**Comment by tudoramariei** [comment]
@horatiubota, please check the Datree notification, seems like the email you used for this commit isn't in your GitHub account. You'll need to either add it to your account or squash the commits and push with the right e-mail 
If you have a question or need more details, please let me know

**Comment by horatiubota** [comment]
@tudoramariei checks pass now.

**Comment by horatiubota** [comment]
@tudoramariei Any updates on this?

**Comment by tudoramariei** [comment]
Hey, @horatiubota! Didn't manage to get to this PR properly.
Also, we started a discussion on the project's main slack channel concerning this repository and the project's architecture. Long story short, we might be giving up on the react framework and keep the whole app as a Django application (front-end and back-end both in the same place).
I'd be glad if you would be able to join the discussion and share your thoughts on the topic. We need more opinions from the developers working on it.
I hope you'll understand. Cheers!

**Comment by catileptic** [comment]
I cloned your PR and resolved the merge conflicts, created a new PR and had it reviewed and merged it, over at #32 .

**Pull request closed without merging**
